### PR TITLE
Created Project Structure and added Validation Msg pack

### PR DESCRIPTION
**Pull request by arti1221**
- Created File Structure for the project
- added Global (used by default) library package
- added custom (for user libraries) library package
- created Validation messages system and global Enum for well known error messages used in the project. NOTE that TEST and TEST_FORMAT are used for testing purposes and will be removed afterwards when the documentation will be added.
- Contains testing with and without formatting in Main runnable
- added package for command lines used by the CLI (part 4 in sys. design documentation)

### CODE REVIEW

**Comment by arti1221** [comment]
This commit is related to task https://github.com/TIS2022-FMFI/web-backups/issues/36

**Review by omaksi — COMMENTED** [review]
I think we shouldn't commit build artifacts (.class files)

**Review by yarvelian — APPROVED** [review]
Approved

**Review by M4jo — APPROVED** [review]
Approved

**Pull request merged**
